### ISSUE TITLE
Create logo

### ISSUE THREAD

**Issue by matiassingers** [javascriptmy/website#4]
We need a logo to rally under!
### inspiration
- [voodootikigod/logo.js](https://github.com/voodootikigod/logo.js) _([registry](https://github.com/voodootikigod/logo.js/blob/master/registry.md))_
- [SingaporeJS](https://github.com/SingaporeJS/logo)
### ideas
- harimau malaya!
  - background color: rgb(0, 0, 0)
  - font color: rgb(255, 240, 0)
  - [tiger icon](http://popradeeo.com/wp-content/uploads/2011/09/Will-Our-Tigers-Roar-Again-1.png)

![kljs-small](https://cloud.githubusercontent.com/assets/938453/7196040/a876a41a-e4fc-11e4-89cc-bfff27d80482.png)

Somebody really good at like Adobe Illustrator or Sketch?
[harimaumalaya.ai](http://cl.ly/2V2H2B1l1Y17)

**Comment by matiassingers** [comment]
| faded (reversed default JS logo colors) | strong (harimau malaya colors) |
| --- | --- |
| ![kljs-faded](https://cloud.githubusercontent.com/assets/938453/7196351/f3219578-e502-11e4-8c18-cedfc4a78c8e.png) | ![kljs-strong](https://cloud.githubusercontent.com/assets/938453/7196352/f347c5d6-e502-11e4-967d-f2b942d9c9b2.png) |

**Comment by matiassingers** [comment]
![kljs-faded-gray](https://cloud.githubusercontent.com/assets/938453/7196629/ea90e382-e507-11e4-9595-7d058da7a781.png)

**Comment by yujinlim** [comment]
wow! pretty sweet!

**Comment by hazimIskandar** [comment]
![untitled-2](https://cloud.githubusercontent.com/assets/10592295/7199648/f058becc-e528-11e4-9252-fce20f245e9c.jpg)

**Comment by hazimIskandar** [comment]
![untitled-2](https://cloud.githubusercontent.com/assets/10592295/7199658/076bc582-e529-11e4-848b-1f4bf41a81da.jpg)

**Comment by soggie** [comment]
I like the tiger version more.

**Comment by zulfajuniadi** [comment]
ofcourse @soggie prefers the putty tat more :cat:

**Comment by matiassingers** [comment]
Created a repo for the logo assets, just need a little help from @soggie to transfer it into this org.

https://github.com/matiassingers/logo

**Comment by matiassingers** [comment]
https://github.com/javascriptmy/logo
